title: 'Header & Footer Scripts'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: header_scipts
            field:
              type: textarea
              display: 'Header Scripts'
              instructions: 'Insert data into the Header'
          -
            handle: footer_script
            field:
              type: textarea
              display: 'Footer Scripts'